const issueActionTypes = Object.freeze({
  LOAD_SUCCESS: 'ISSUE/LOAD_SUCCESS',
  LOAD_REQUEST: 'ISSUE/LOAD_REQUEST',
  LOAD_ERROR: 'ISSUE/LOAD_ERROR',

  CLEAR: 'ISSUE/CLEAR',

  ADD_REQUEST: 'ISSUE/ADD_REQUEST',
  ADD_SUCCESS: 'ISSUE/ADD_SUCCESS',
  ADD_ERROR: 'ISSUE/ADD_ERROR',

  SET_IS_ISSUE_SAVED: 'ISSUE/SET_IS_ISSUE_SAVED',

  DELETE_REQUEST: 'ISSUE/DELETE_REQUEST',
  DELETE_SUCCESS: 'ISSUE/DELETE_SUCCESS',
  DELETE_ERROR: 'ISSUE/DELETE_ERROR',

  SET_IS_ISSUE_DELETED: 'ISSUE/SET_IS_ISSUE_DELETED',

  EDIT_REQUEST: 'ISSUE/EDIT_REQUEST',
  EDIT_SUCCESS: 'ISSUE/EDIT_SUCCESS',
  EDIT_ERROR: 'ISSUE/EDIT_ERROR',

  SET_IS_ISSUE_EDITED: 'ISSUE/SET_IS_ISSUE_EDITED',

  CLEAR_ERRORS: 'ISSUE/CLEAR_ERRORS',
});

export default issueActionTypes;
