const projectActionTypes = Object.freeze({
  LOAD_REQUEST: 'PROJECT/LOAD_REQUEST',
  LOAD_SUCCESS: 'PROJECT/LOAD_SUCCESS',
  LOAD_ERROR: 'PROJECT/LOAD_ERROR',

  CLEAR: 'PROJECT/CLEAR',

  ADD_REQUEST: 'PROJECT/ADD_REQUEST',
  ADD_SUCCESS: 'PROJECT/ADD_SUCCESS',
  ADD_ERROR: 'PROJECT/ADD_ERROR',

  SET_IS_PROJECT_SAVED: 'PROJECT/SET_IS_PROJECT_SAVED',

  DELETE_REQUEST: 'PROJECT/DELETE_REQUEST',
  DELETE_SUCCESS: 'PROJECT/DELETE_SUCCESS',
  DELETE_ERROR: 'PROJECT/DELETE_ERROR',

  SET_IS_PROJECT_DELETED: 'PROJECT/SET_IS_PROJECT_DELETED',

  CLEAR_ERRORS: 'PROJECT/CLEAR_ERRORS',
});

export default projectActionTypes;
