const projectActionTypes = Object.freeze({
  LOAD_REQUEST: 'PROJECT/LOAD_REQUEST',
  LOAD_SUCCESS: 'PROJECT/LOAD_SUCCESS',
  LOAD_ERROR: 'PROJECT/LOAD_ERROR',

  CLEAR: 'PROJECT/CLEAR',

  ADD_REQUEST: 'PROJECT/ADD_REQUEST',
  ADD_SUCCESS: 'PROJECT/ADD_SUCCESS',
  ADD_ERROR: 'PROJECT/ADD_ERROR',
});

export default projectActionTypes;
