const authActionTypes = Object.freeze({
  INIT_SUCCESS: 'AUTH/INIT_SUCCESS',
  INIT_ERROR: 'AUTH/INIT_ERROR',

  REGISTER_REQUEST: 'AUTH/REGISTER_REQUEST',
  REGISTER_SUCCESS: 'AUTH/REGISTER_SUCCESS',
  REGISTER_ERROR: 'AUTH/REGISTER_ERROR',

  CLEAR_ERRORS: 'AUTH/CLEAR_ERRORS',
  LOGOUT: 'AUTH/LOGOUT',

  LOGIN_REQUEST: 'AUTH/LOGIN_REQUEST',
  LOGIN_SUCCESS: 'AUTH/LOGIN_SUCCESS',
  LOGIN_ERROR: 'AUTH/LOGIN_ERROR',

  LOGIN_SET_IS_LOGGED_IN: 'AUTH/LOGIN_SET_IS_LOGGED_IN',
});

export default authActionTypes;
