const authActionTypes = Object.freeze({
  REGISTER_REQUEST: 'AUTH/REGISTER_REQUEST',
  REGISTER_SUCCESS: 'AUTH/REGISTER_SUCCESS',
  REGISTER_ERROR: 'AUTH/REGISTER_ERROR',

  CLEAR_ERRORS: 'AUTH/CLEAR_ERRORS',

  LOGIN_REQUEST: 'AUTH/LOGIN_REQUEST',
  LOGIN_SUCCESS: 'AUTH/LOGIN_SUCCESS',
  LOGIN_ERROR: 'AUTH/LOGIN_ERROR',
});

export default authActionTypes;
