name: backend

defaults:
  run:
    working-directory: ./backend

on:
  pull_request:
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_HOST: localhost
      DB_USER: user123
      DB_PASSWORD: password123
      DB_NAME: issue_tracker

    strategy:
      matrix:
        node-version: [14.x]

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: ${{ env.DB_NAME }}
          MYSQL_USER: ${{ env.DB_USER }}
          MYSQL_PASSWORD: ${{ env.DB_PASSWORD }}
          MYSQL_ROOT_PASSWORD: rootpw
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=10

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn --frozen-lockfile
      - run: yarn migrate up

      - run: yarn test

      - run: yarn lint
