name: backend

defaults:
  run:
    working-directory: ./backend
    env:
      DB_HOST: localhost
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: issue_tracker

on:
  pull_request:
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: issue_tracker
          MYSQL_ROOT_PASSWORD:
          MYSQL_USER: root
          MYSQL_PASSWORD: password
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        port:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn --frozen-lockfile

      - run: yarn test

      - run: yarn lint
